// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace game {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvKoIBCglFcnJvckNvZGUSFQoRRXJyb3JDb2RlX1N1Y2Nl",
            "c3MQABIVChFFcnJvckNvZGVfRmFpbHVyZRABEiUKIUVycm9yQ29kZV9BbHJl",
            "YWR5Q3JlYXRlZENoYXJhY3RlchACEiAKHEVycm9yQ29kZV9BbHJlYWR5RGVm",
            "aW5lZE5hbWUQAyoxCghSYW5rVHlwZRIRCg1SYW5rVHlwZV9Ob25lEAASEgoO",
            "UmFua1R5cGVfU3RhZ2UQASpMCgpSZXdhcmRUeXBlEhMKD1Jld2FyZFR5cGVf",
            "Tm9uZRAAEhMKD1Jld2FyZFR5cGVfSXRlbRABEhQKEFJld2FyZFR5cGVfU2tp",
            "bGwQAkIHqgIEZ2FtZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::game.ErrorCode), typeof(global::game.RankType), typeof(global::game.RewardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    [pbr::OriginalName("ErrorCode_Success")] Success = 0,
    [pbr::OriginalName("ErrorCode_Failure")] Failure = 1,
    [pbr::OriginalName("ErrorCode_AlreadyCreatedCharacter")] AlreadyCreatedCharacter = 2,
    [pbr::OriginalName("ErrorCode_AlreadyDefinedName")] AlreadyDefinedName = 3,
  }

  public enum RankType {
    [pbr::OriginalName("RankType_None")] None = 0,
    [pbr::OriginalName("RankType_Stage")] Stage = 1,
  }

  public enum RewardType {
    [pbr::OriginalName("RewardType_None")] None = 0,
    [pbr::OriginalName("RewardType_Item")] Item = 1,
    [pbr::OriginalName("RewardType_Skill")] Skill = 2,
  }

  #endregion

}

#endregion Designer generated code
