// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/network.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace game {
  public static partial class PlayerNetwork
  {
    static readonly string __ServiceName = "playerNetwork.PlayerNetwork";

    static readonly grpc::Marshaller<global::game.AuthRequest> __Marshaller_playerNetwork_AuthRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.AuthRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.AuthResponse> __Marshaller_playerNetwork_AuthResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.AuthResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.PlayerDataList> __Marshaller_playerNetwork_PlayerDataList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.PlayerDataList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.RegionData> __Marshaller_playerNetwork_RegionData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.RegionData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.PlayerData> __Marshaller_playerNetwork_PlayerData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.PlayerData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.CreatePlayerRequest> __Marshaller_playerNetwork_CreatePlayerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.CreatePlayerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.CreatePlayerResponse> __Marshaller_playerNetwork_CreatePlayerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.CreatePlayerResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.UpdateStageRequest> __Marshaller_playerNetwork_UpdateStageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.UpdateStageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.UpdateStageResponse> __Marshaller_playerNetwork_UpdateStageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.UpdateStageResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.StreamServerEventsResponse> __Marshaller_playerNetwork_StreamServerEventsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.StreamServerEventsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.ChatRequest> __Marshaller_playerNetwork_ChatRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.ChatRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.ChatResponse> __Marshaller_playerNetwork_ChatResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.ChatResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::game.RankList> __Marshaller_playerNetwork_RankList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::game.RankList.Parser.ParseFrom);

    static readonly grpc::Method<global::game.AuthRequest, global::game.AuthResponse> __Method_GetAuth = new grpc::Method<global::game.AuthRequest, global::game.AuthResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAuth",
        __Marshaller_playerNetwork_AuthRequest,
        __Marshaller_playerNetwork_AuthResponse);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.PlayerDataList> __Method_GetRegionPlayerDataList = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.PlayerDataList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRegionPlayerDataList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_playerNetwork_PlayerDataList);

    static readonly grpc::Method<global::game.RegionData, global::game.PlayerData> __Method_LoginPlayerData = new grpc::Method<global::game.RegionData, global::game.PlayerData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoginPlayerData",
        __Marshaller_playerNetwork_RegionData,
        __Marshaller_playerNetwork_PlayerData);

    static readonly grpc::Method<global::game.CreatePlayerRequest, global::game.CreatePlayerResponse> __Method_CreatePlayer = new grpc::Method<global::game.CreatePlayerRequest, global::game.CreatePlayerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreatePlayer",
        __Marshaller_playerNetwork_CreatePlayerRequest,
        __Marshaller_playerNetwork_CreatePlayerResponse);

    static readonly grpc::Method<global::game.UpdateStageRequest, global::game.UpdateStageResponse> __Method_UpdateStage = new grpc::Method<global::game.UpdateStageRequest, global::game.UpdateStageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateStage",
        __Marshaller_playerNetwork_UpdateStageRequest,
        __Marshaller_playerNetwork_UpdateStageResponse);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.StreamServerEventsResponse> __Method_ServerStreamServerEvents = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.StreamServerEventsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ServerStreamServerEvents",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_playerNetwork_StreamServerEventsResponse);

    static readonly grpc::Method<global::game.ChatRequest, global::game.ChatResponse> __Method_Chat = new grpc::Method<global::game.ChatRequest, global::game.ChatResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Chat",
        __Marshaller_playerNetwork_ChatRequest,
        __Marshaller_playerNetwork_ChatResponse);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.RankList> __Method_GetTopRankList = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::game.RankList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTopRankList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_playerNetwork_RankList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::game.NetworkReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for PlayerNetwork</summary>
    public partial class PlayerNetworkClient : grpc::ClientBase<PlayerNetworkClient>
    {
      /// <summary>Creates a new client for PlayerNetwork</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlayerNetworkClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PlayerNetwork that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlayerNetworkClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlayerNetworkClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlayerNetworkClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::game.AuthResponse GetAuth(global::game.AuthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAuth(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.AuthResponse GetAuth(global::game.AuthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAuth, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.AuthResponse> GetAuthAsync(global::game.AuthRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAuthAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.AuthResponse> GetAuthAsync(global::game.AuthRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAuth, null, options, request);
      }
      public virtual global::game.PlayerDataList GetRegionPlayerDataList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRegionPlayerDataList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.PlayerDataList GetRegionPlayerDataList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRegionPlayerDataList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.PlayerDataList> GetRegionPlayerDataListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRegionPlayerDataListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.PlayerDataList> GetRegionPlayerDataListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRegionPlayerDataList, null, options, request);
      }
      public virtual global::game.PlayerData LoginPlayerData(global::game.RegionData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginPlayerData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.PlayerData LoginPlayerData(global::game.RegionData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoginPlayerData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.PlayerData> LoginPlayerDataAsync(global::game.RegionData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginPlayerDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.PlayerData> LoginPlayerDataAsync(global::game.RegionData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoginPlayerData, null, options, request);
      }
      public virtual global::game.CreatePlayerResponse CreatePlayer(global::game.CreatePlayerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreatePlayer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.CreatePlayerResponse CreatePlayer(global::game.CreatePlayerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreatePlayer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.CreatePlayerResponse> CreatePlayerAsync(global::game.CreatePlayerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreatePlayerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.CreatePlayerResponse> CreatePlayerAsync(global::game.CreatePlayerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreatePlayer, null, options, request);
      }
      public virtual global::game.UpdateStageResponse UpdateStage(global::game.UpdateStageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateStage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.UpdateStageResponse UpdateStage(global::game.UpdateStageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateStage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.UpdateStageResponse> UpdateStageAsync(global::game.UpdateStageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateStageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.UpdateStageResponse> UpdateStageAsync(global::game.UpdateStageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateStage, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::game.StreamServerEventsResponse> ServerStreamServerEvents(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ServerStreamServerEvents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::game.StreamServerEventsResponse> ServerStreamServerEvents(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ServerStreamServerEvents, null, options, request);
      }
      public virtual global::game.ChatResponse Chat(global::game.ChatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Chat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.ChatResponse Chat(global::game.ChatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Chat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.ChatResponse> ChatAsync(global::game.ChatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.ChatResponse> ChatAsync(global::game.ChatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Chat, null, options, request);
      }
      public virtual global::game.RankList GetTopRankList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTopRankList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::game.RankList GetTopRankList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTopRankList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::game.RankList> GetTopRankListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTopRankListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::game.RankList> GetTopRankListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTopRankList, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlayerNetworkClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlayerNetworkClient(configuration);
      }
    }

  }
}
#endregion
